### ISSUE TITLE
Searching new maintainer

### ISSUE THREAD

**Issue by malkusch** [php-lock/lock#13]
This project searches for a new maintainer. Please volunteer.

**Comment by willemstuursma** [comment]
Are you looking to step back altogether or for someone to share responsibilities with?

There's also the recently released symfony/lock, which offers similar features but also allows you to extend the lock from within the lock.

**Comment by malkusch** [comment]
> Are you looking to step back altogether or for someone to share responsibilities with?

I'm looking for someone or more who would own this project. Step back it is.

> There's also the recently released symfony/lock, which offers similar features but also allows you to extend the lock from within the lock.

It's about the users of this library. I don't want to create pain for them, so I hope to find someone who will be there for them. Otherwise yes, they will have to look for an alternative.

**Comment by b1rdex** [comment]
+1 for deprecating this completely and pointing to `symfony/lock`.
As for pain of transition — it is possible to write adapter, that will accept symfony lock factory as implementation.

**Comment by malkusch** [comment]
> +1 for deprecating this completely and pointing to symfony/lock.

That's something a new maintainer can be responsible for. Currently symfony/lock offers less implementations. Some people might get unhappy about that.

**Comment by willemstuursma** [comment]
I'll take it on @malkusch.

**Comment by malkusch** [comment]
I wanted to transfer it to you, but you have already a repository called "lock".

**Comment by willemstuursma** [comment]
I have renamed my `lock` repository.

**Comment by malkusch** [comment]
I still can't transfer ownership:

> willemstuursma already has a repository in the malkusch/lock network

I guess renaming doesn't work as it keeps a redirect from your old repository. I suggest the best would be you just delete your repository. You can then push your commits from your local copy back. Also I will need your packagist username.

**Comment by malkusch** [comment]
To make it easier, I transfered this project into a new organization. Now it's yours. Thank you.

**Comment by willemstuursma** [comment]
Cheers.
