### ISSUE TITLE
Check if the lock is taken

### ISSUE THREAD

**Issue by rhutanu90** [php-lock/lock#21]
Hi! We encountered a situation when we would like to terminate all the calls when a locked call is already in execution (instead of waiting). @malkusch do you plan to extend the library with this feature in the near future? :+1:

**Comment by willemstuursma** [comment]
You mean, testing if the lock is taken, and then aborting?

**Comment by TheLevti** [comment]
That would also be a solution. We use predis locks. In some cases we don't want to wait until the lock is released, but abort the request if another process is already holding that lock.

**Comment by rhutanu90** [comment]
Yes, check if the lock is taken and if so throw an exception

**Comment by tsmgeek** [comment]
If the Loop class had an ability to pass a flag to disable retries or set X retries instead of using timeout this could help this out etc.

**Comment by georgegg** [comment]
Hi. I would avoid to introduce a second timeout because funky things might happen. I would suggest the use of a flag to enable/disable the loop to execute more than once or till the locks ttl expire. 
Is this thread active or rather do you see value in this feature?

**Comment by fredericgboutin-yapla** [comment]
"workaround", use Symfony Lock instead - https://symfony.com/doc/5.x/components/lock.html#usage

**Comment by mvorisek** [comment]
closing as duplicate of #11
