### ISSUE TITLE
No access to code return value in case of ExecutionOutsideLockException or LockReleaseException

### ISSUE THREAD

**Issue by Furgas** [php-lock/lock#28]
When `LockReleaseException` or `ExecutionOutsideLockException` is thrown there is no way to access the return value of the code block (it was executed).

Following change to `LockMutex::synchronized()` comes to mind:

```php
    public function synchronized(callable $code)
    {
        $this->lock();

        $result = null;
        try {
            $result = $code();
        } finally {
	        try {
		        $this->unlock();
	        } catch (ExecutionOutsideLockException|LockReleaseException $e) {
		        $e->setCodeResult($result);
		        throw $e;
	        }
        }

        return $result;
    }
```

Also `setCodeResult` and `getCodeResult` should be added to both exception classes.

Of course a library user can always extend specific `LockMutex` subclass (ex. `PredisMutex`) and override the `synchronized()` method to deal with this problem, but maybe it's worth incorporating directly into the library.

**Comment by willemstuursma** [comment]
It sounds nice @Furgas, would you be willing to create a PR?

**Comment by willemstuursma** [comment]
On `master` would be great, thanks.

**Comment by Furgas** [comment]
Created #29.

**Comment by willemstuursma** [comment]
> Regarding the case when the executed code threw an exception, wouldn't it make more sense to set that exception as previous exception when the LockReleaseException is thrown?

No, that should be the exception that caused the `LockReleaseException`. For example, a failure to execute the query to release the lock if a database server is used for storing locks.

There can be two exceptions: e.g. one is thrown by the code within the lock, then the lock is released, but that failed too.
