### ISSUE TITLE
Unit test fails with "parallel" extension

### ISSUE THREAD

**Issue by reeperbahnause** [php-lock/lock#37]
The following PHPUnit test fails if I try to use [parallel threads](https://www.php.net/manual/de/parallel.run.php)

I'm using `php-lock version 2.1` on `windows` with `php version 7.4.6`  

If I deactivate the `$this->mutex->synchronized` function by commenting out the function the test is executed without an error.
Does anyone have an idea whats wrong with my test case?

```php
<?php
namespace Squeeze;

use Exception;
use malkusch\lock\mutex\FlockMutex;
use PHPUnit\Framework\TestCase;

class ThreadLockTest extends TestCase
{

    /**
     * @var FlockMutex
     */
    private $mutex;

    /**
     * @var resource
     */
    private $file;

    protected function setUp(): void
    {
        parent::setUp();

        $this->file = __DIR__ . DIRECTORY_SEPARATOR . 'flock';
        $this->mutex = new FlockMutex(fopen($this->file, 'w'), 1);
    }

    protected function tearDown(): void
    {
        unlink($this->file);

        parent::tearDown();
    }

    public function testThreadLock(): void
    {
        $syncFunction = function ($i) {
            try {
                require_once __DIR__ . '/../../../bootstrap/app.php';
                echo $i .' Running ' . PHP_EOL;
                return $this->mutex->synchronized(function () use ($i) : string {
                    sleep(1);
                    return $i .' Finished.' . PHP_EOL;
                });
            } catch (Exception $e) {
                return $e->getMessage() . PHP_EOL;
            }
        };

        $results = array();
        for ($i = 1; $i < 6; $i++) {
            $results[] = \parallel\run($syncFunction, array($i));
        }

        foreach ($results as $item) {
            echo $item->value();
        }
    }
}
```

**Comment by willemstuursma** [comment]
Try creating the mutex inside `$syncFunction`.

**Comment by mvorisek** [comment]
@reeperbahnause would you mind sending a PR?

**Comment by mvorisek** [comment]
I copied your repro/test code to CI - https://github.com/php-lock/lock/commit/b00e0e901648435de3d64cae2228aa3c029e83a6.

and hit https://github.com/krakjoe/parallel/issues/337. Let's wait until this MM issue is fixed.

**Comment by mvorisek** [comment]
I am closing this issue for now as I am not sure how `krakjoe/parallel` ext should behave. It seems the main memory is not shared with the child thread fully or there is some issue in that ext at least. If there will be some positive progress in https://github.com/krakjoe/parallel/issues/337 we can reopen this this anytime.
