### ISSUE TITLE
Loop::execute throws TimeoutException even though lock was acquired

### ISSUE THREAD

**Issue by felixkempf** [php-lock/lock#47]
(We are using php 7.3.22 on Linux together with `php-lock` v2.1, but it seems this issue persists in v2.2 as well)

I'm not quite sure if this is desired behavior, but I want to talk about Loop::execute():

Let's suppose the call `$result = $code();` was successful, meaning `$code()` called `Loop::end()` and had side effects, **but** its successful execution took longer than `$this->timeout`. 

In that case
```
if (microtime(true) >= $deadline) {
        throw TimeoutException::create($this->timeout);
}
```
which appears after the `for` loop, would still throw a TimeoutException, which seems counterintuitive to me.

A possible fix could be to only throw if additionally `$this->looping` is true:
```
if (microtime(true) >= $deadline && $this->looping) {
        throw TimeoutException::create($this->timeout);
}
```

See [LongLockTest.txt](https://github.com/php-lock/lock/files/6523226/LongLockTest.txt) for a quick unit test

**Comment by willemstuursma** [comment]
It looks to me like you are right. 

I think the method could be improved by replacing the `break` statement with a `return` statement.

The if statement on line 122 could then be dropped.

**Comment by willemstuursma** [comment]
If we acquire the lock, even if it takes slightly longer than the timeout, that's not an error.

It does not make sense to acquire the lock and then throw an exception, without releasing the lock.

**Comment by felixkempf** [comment]
>If we acquire the lock, even if it takes slightly longer than the timeout, that's not an error.
>It does not make sense to acquire the lock and then throw an exception, without releasing the lock.

Yes, well put. I'm glad you agree.

Also, thank you for the quick response and fix. 
I'll take the freedom to close the issue. Please reopen if you still need anything from me in this regard.

**Comment by willemstuursma** [comment]
Thanks, you could help me by reviewing #48.
