### ISSUE TITLE
PostgreSQL - Numeric value out of range

### ISSUE THREAD

**Issue by nekulin** [php-lock/lock#50]
php 8.1
PostgreSQL 12.9

`SQLSTATE[22003]: Numeric value out of range: 7 ERROR:  value "4132123129" is out of range for type integer`

**Comment by mvorisek** [comment]
@nekulin please provide minimal repro or at least a full stack trace.

**Comment by mvorisek** [comment]
In https://github.com/php-lock/lock/pull/64 the name to lock int keys impl. was cleaned up.

Orignal `unpack('i', ...)` is defined like "signed integer (machine dependent size and byte order)".

I doubt `int` was defined as 64-bit in your case as I was not able to reproduce it https://3v4l.org/S5Pen on my x86 nor x64 systems.

It is weird as PostgreSQL does not even support unsigned integers [1] and thus I would expect the same from PDO.

[1] https://www.postgresql.org/docs/current/datatype-numeric.html
