### ISSUE TITLE
Add support for PHPUnit 11

### ISSUE THREAD

**Issue by jvalleroy** [php-lock/lock#56]
I would like to update the Debian package to be compatible with PHPUnit 11 (in experimental branch currently): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1070567

I have identified a few of the changes needed:
- Add static to test providers.
  - Change `$this->` to `self::`.
  - Need to find a replacement for getMockForAbstractClass. Maybe a callback that is called within the test case.
- Change setMethods to onlyMethods or addMethods.

There could be additional changes needed, this is just what I found so far.

**Comment by mvorisek** [comment]
@reeperbahnause would you mind sending a PR?

**Comment by mvorisek** [comment]
I have landed https://github.com/php-lock/lock/commit/22d4b4253b4472659092964e761cbe022df71081 which should cover the majority of LoC changes needed.
