### ISSUE TITLE
flock with timeout support

### ISSUE THREAD

**Issue by glensc** [php-lock/lock#6]
I like [FlockMutex](https://github.com/malkusch/lock#flockmutex) because it work on kernel level and is reliable.

however there's the problem that acquiring the lock makes program wait forever. I wish to get error "unable to obtain lock withing timeout"

for [flock](http://php.net/flock) there's `LOCK_NB` flag which can be used.

ps: [SemaphoreMutex](https://github.com/malkusch/lock#semaphoremutex) has similar issue

**Comment by hidenorigoto** [comment]
+1 for SemaphoreMutex

**Comment by malkusch** [comment]
Having a timeout is actually a nice feature. `LOCK_NB` would turn the implementation into a busy waiting lock and suffer from being inacurate. I will consider this option as a last resort. But first I will see if [`pcntl_alarm`](http://php.net/manual/en/function.pcntl-alarm.php) might be a better option.

**Comment by glensc** [comment]
i don't see how `pcntl_alarm` helps here, it's just weird way of saying `sleep(2)`.

i'd love to see the timeout being implemented, as for inaccuracy and race conditions, i think the sleep and retry should be somehow randomized and exponential. 

and as LOCK_NB would move the locking to "userspace" from "kernel", it should be enabled only when timeout > 0 so previous behavior could be used.

**Comment by malkusch** [comment]
> i don't see how pcntl_alarm helps here

It's a very effective way to put a timeout on `flock()`:

```
pcntl_signal(SIGALRM, function() {});
pcntl_alarm(3);
try {
    if (!flock($handle, LOCK_EX)) {
        throw new \Exception("Timeout after 3 seconds");
    }
} finally {
    pcntl_alarm(0);
    pcntl_signal_dispatch();
    pcntl_signal(SIGALRM, SIG_DFL);
}
```

Unfortunately [it doesn't seem to be portable](http://stackoverflow.com/questions/40710549/is-there-a-portable-way-to-put-a-timeout-on-flock), which is the whole point about flock(). I guess I'll chose a hybrid implementation, that is sending the signal, and falling back to busy waiting if `pcntl` is not available.

**Comment by glensc** [comment]
ah, it makes flock "timeout" without `LOCK_NB`, i see now

**Comment by glensc** [comment]
https://symfony.com/blog/new-in-symfony-3-3-lock-component

[symfony/lock](https://symfony.com/doc/3.4/components/lock.html) seems to have timeout support, it has flock backend. will test if it suits.

**Comment by glensc** [comment]
update: symfony/lock: blocking doesn't support timeout and for nonblocking mode one would need to implement timeout themselves: https://github.com/symfony/symfony/issues/25418

**Comment by glensc** [comment]
update2: seems flock doesn't support timeout: https://symfony.com/doc/3.4/components/lock.html#available-stores and nonblocking mode i misread the implementation (because i looked at internal code which were void: FlockStore::save, FlockStore::waitAndSave)

**Comment by glensc** [comment]
@TheLevti add link to your quoted reference. don't strip credits.

**Comment by TheLevti** [comment]
http://php.net/manual/en/intro.pcntl.php

**Comment by willemstuursma** [comment]
Timeout support has been added to `FlockMutex` in the `master` branch.

It uses PCNTL if possible and busy waiting if not.

It's not production ready! But is't ready for some testing. Please report any issues here.

**Comment by TheLevti** [comment]
With php7.1+ it is possible to get the current signal handler to not just overwrite a possible existing one. http://php.net/manual/en/function.pcntl-signal-get-handler.php

So at least for php7.1+ the recommendation to not use the flock mutex when signal handler are used, can be changed.

**Comment by willemstuursma** [comment]
@TheLevti I'm not extremely familiair with the signal handling. Could you incorporate this in a PR?

The changes should go into `\malkusch\lock\util\PcntlTimeout::timeBoxed`.

**Comment by TheLevti** [comment]
> @TheLevti I'm not extremely familiair with the signal handling. Could you incorporate this in a PR?
> 
> The changes should go into `\malkusch\lock\util\PcntlTimeout::timeBoxed`.

Your latest additions to https://github.com/php-lock/lock/pull/26 should solve this.
