### ISSUE TITLE
RedisMutex unnecessarily generating new tokens

### ISSUE THREAD

**Issue by yuloh** [php-lock/lock#9]
I'm having an issue I can't reliably reproduce.  It _seems like_ the lock is allowing concurrent access but I'm not 100% sure.

I noticed the [RedisMutex generates a new token each time](https://github.com/malkusch/lock/blob/master/classes/mutex/RedisMutex.php#L101) it tries to acquire the lock.

Looking at [Antirez's implementation](https://github.com/antirez/redlock-rb/blob/master/redlock.rb#L56) it looks like it keeps retrying with the same token.

Generating a new token each time increases the likelihood of deleting the key belonging to another process, since you now have multiple tries to generate a collision instead of just one.

I _think_ this issue combined with `rand` not being very random is causing collisions fairly often.

**Comment by yuloh** [comment]
Update: I added a call to `$mutex->seedRandom(random_int(PHP_INT_MIN, PHP_INT_MAX))` and haven't seen a collision since.  I'm not using a forked process; these are separate PHP processes.

**Comment by willemstuursma** [comment]
Thanks for reporting. With the improved token generation, it won't matter to reuse or to generate new tokens for every try.
